### ISSUE TITLE
bodyText is displayed 8 times

### ISSUE THREAD

**Issue by JakubNeukirch** [talamaska/onboarding_overlay#14]
In stepper.dart if I have `autoSizeTexts: false` my bodyText is displayed 8 times, here is the place in code: [stepper.dart](https://github.com/talamaska/onboarding_overlay/blob/1eaad6562a48bed77d19de65f7d510f840d5f761/lib/src/stepper.dart#L401). What is it for?

When I use `autoSizeTexts: true` the text is displayed once but it has yellow underline like it does not have Material as parent.

**Comment by talamaska** [comment]
Ups. My bad, i though I have removed that. Will publish a new version today with a fix. Thanks for reporting this.

**Comment by talamaska** [comment]
@JakubNeukirch Are you trying to use the package in a non MaterialApp?

**Comment by JakubNeukirch** [comment]
@talamaska I am using MaterialApp. The problem with underline occurrs only when autoSizeTexts is true. When it is false, it does not happen

**Comment by talamaska** [comment]
Would you like to post a sample code reproducing the issue. Do you see the issue in the example app as well?

**Comment by Macacoazul01** [comment]
I'm having the same problem with `onboarding_overlay: ^2.3.1`

Sample code:

```
OnboardingStep(
  focusNode: focusList[7],
  title: 'Novas Cobranças',
  bodyText: 'Crie novas cobranças aqui!',
  titleTextStyle: titleStyle(cor: Colors.black),
  bodyTextStyle: conteudoStyle(cor: Colors.black,bold: false),
  overlayColor: cellpowder,
  margin: EdgeInsets.fromLTRB(largDez,altDez,largCinco*3,altCinco*3),
  shape: const CircleBorder(),
  fullscreen: false,
  overlayShape: const CircleBorder(),
),
```

The result: 

![Screenshot_1636497160](https://user-images.githubusercontent.com/57464965/141016233-e53a265a-fa3c-44b7-bdf5-d4eacd41680a.png)

**Comment by Macacoazul01** [comment]
with onboarding_overlay: ^2.3.3 the duplication of bodyText is fixed, but i'm still seeing the yellow line:


![Screenshot_1636497160](https://user-images.githubusercontent.com/57464965/141016782-16766e60-7b5b-4bd8-b588-f9eabffca592.png)

Also for this one there's a strange behavior of the circle overlay:

```
OnboardingStep(
  focusNode: focusList[0],
  textAlign: TextAlign.center,
  title: 'Bem vindo a Bianca!',
  bodyText: 'Toque na tela para começar o tutorial',
  titleTextStyle: titleStyle(),
  bodyTextStyle: conteudoStyle(bold: false),
  fullscreen: false,
  shape: const CircleBorder(),
  overlayShape: const CircleBorder(),
  overlayColor: biancaAzul
),
```


![Screenshot_1636497587](https://user-images.githubusercontent.com/57464965/141017031-622d472e-0223-458d-b823-e8c46b083677.png)

**Comment by Macacoazul01** [comment]
Tried changing from master to stable but the error still happens

**Comment by Macacoazul01** [comment]
Setting 
```
titleTextStyle: null
bodyTextStyle: null
```
Fix the lines problem.

**Comment by Macacoazul01** [comment]
Tried replacing my dynamic `titleStyle` and `conteudoStyle` for `TextStyle(color: Colors.red),` but the error still happens

**Comment by talamaska** [comment]
@Macacoazul01 Please add minimal code replicating the issue. I don't have this issue in the example app.
Also please create a separate issue for the shape problems and add minimal code replicating the issue with the shape.

**Comment by talamaska** [comment]
Ok i think i see the issue with the underline text, will see what i can do. and i think I have figured out the second issue about the position of the overlay, is that you don't set the focusNode on any element? Still please create another issue for it, so i can track it and mention it in the Change log.

**Comment by Macacoazul01** [comment]
I've created another issue for the position
