### ISSUE TITLE
bodyTextColor and titleTextColor

### ISSUE THREAD

**Issue by Macacoazul01** [talamaska/onboarding_overlay#18]
using `onboarding_overlay: ^2.3.4`

It doesn't make sense to have `bodyTextColor` and `titleTextColor` parameters on OnboardingStep() as the text color can be set on `bodyTextStyle` and `titleTextStyle` parameters using TextStyle(color: Colors.red) for example.

Also if i use both text style and text color, the text style is the one applied, so it can confuse the user:

with both:

```
OnboardingStep(
  focusNode: focusNodes[0],
  title: "Or no widget at all! You're all done!",
  bodyText: "Or no widget at all! You're all done!",
  margin: EdgeInsets.zero,
  labelBoxPadding: const EdgeInsets.all(8.0),
  shape: const CircleBorder(),
  fullscreen: false,
  overlayShape: const CircleBorder(),
  bodyTextStyle: TextStyle(color: Colors.red),
  bodyTextColor: Colors.amber,
),
```
![Screenshot_1636559205](https://user-images.githubusercontent.com/57464965/141145541-7b6f9024-6adb-4b14-b4b3-f466542becf5.png)

textColor only:

```
OnboardingStep(
  focusNode: focusNodes[0],
  title: "Or no widget at all! You're all done!",
  bodyText: "Or no widget at all! You're all done!",
  margin: EdgeInsets.zero,
  labelBoxPadding: const EdgeInsets.all(8.0),
  shape: const CircleBorder(),
  fullscreen: false,
  overlayShape: const CircleBorder(),
  bodyTextColor: Colors.amber,
),
```

![Screenshot_1636559222](https://user-images.githubusercontent.com/57464965/141145568-e85f0a5c-5bf9-474b-ab75-95e69360ad36.png)

**Comment by talamaska** [comment]
@Macacoazul01 Would you agree that this is mostly a documentation issue. Is it going to be sufficient to add inline doc for the style props that they have property over the color properties?

**Comment by talamaska** [comment]
@Macacoazul01 If i add different asserts, this might be treated as a breaking change and I'm not sure I want to do this.

**Comment by Macacoazul01** [comment]
If people are trying to use both properties together, the code is already "breaking" hahahah, so it's not a problem if you follow this path.

The first option is also a breaking change as you will remove something that someone maybe is using on the current version.

I don't know if most people uses this shortcut to change only the color or uses the textstyle way. I'm using the textstyle because i need the textsize to change as the device screen size changes, and also to control this variation to be similar to the other texts on my app.

**Comment by talamaska** [comment]
I have published 2.3.5-pre.1. In theory you can still not set the color in the TextStyle and then the color will be taken from the color property. I'm not inclined of removing the color props. I mostly use only them.

**Comment by talamaska** [comment]
Also keep in mind that orientation change might create some unexpected issues, like the label box could be position on the bottom of it instead of on top or inverse. Some items could be positioned outside of the viewport. I'm working in a different branch to try to resolve some of those issues, like providing and alternative Arrow position and scrolling the item inside of the viewport, that it is I can get a Scrollable in the context. This works in the example app, but people can do a bunch of weird stuff like using slivers and nested scrollables and there is nothing I can do.  i would lock the orientation while the onboarding is running and enable it again when the onboarding ends.

**Comment by Macacoazul01** [comment]
> I have published 2.3.5-pre.1. In theory you can still not set the color in the TextStyle and then the color will be taken from the color property. I'm not inclined of removing the color props. I mostly use only them. Please verify if that works for you.

If the dev sets the color on both what will happen?
An assert shows up? The textstyle color have the priority? There's anything on the docs to tell the dev what will occur?

**Comment by talamaska** [comment]
There is. Check the doc for the titleTextProperty. No new asserts. The case
of setting both is completly valid, as well as setting only one of them.
Even setting the style property without a color is valid. The docs says
that if we set the color via color property and the text style property,
the color in text style property takes precedence.

**Comment by talamaska** [comment]
https://pub.dev/documentation/onboarding_overlay/2.3.5-pre.1/onboarding_overlay/OnboardingStep/titleTextStyle.html
