### ISSUE TITLE
Add getter isVisible and currentStep to OnboardingState

### ISSUE THREAD

**Issue by guenth39** [talamaska/onboarding_overlay#20]
For me, it would be very helpful to know if an overlay is currently displayed. Maybe a getter `currentStep` would also be interesting, then you don't have to use the `onChange` listener and save the index separate.  
Or is there already such a possibility and I have not found it yet?

Best Regards

**Comment by talamaska** [comment]
No there isn't such possibility. I'll see what I can do.

**Comment by talamaska** [comment]
@guenth39 check latest changes in https://github.com/talamaska/onboarding_overlay/tree/feature/provide-builder

**Comment by guenth39** [comment]
Works like expected ✅ Thanks a lot!

**Comment by talamaska** [comment]
ok will release a prelease tomorrow with one more feature that I have in the stack - a pulsing animation around the hole of the focused widget. So that more people can eventually test from pub.dev

**Comment by talamaska** [comment]
Published a [v3.0.0-pre.1](https://pub.dev/packages/onboarding_overlay/versions/3.0.0-pre.1). Give it a shot again when you have time. This release include all your requested features, plus some breaking changes and other features. Refer to the changelog for a precise list.

**Comment by guenth39** [comment]
I just tested it and I noticed the following things:

1. You write `nextStep` and `close` work only if `manualControl == true`, but for me they always work. But I think that is good and important, especially that `close` always works! `manualControl == false` disables from my point of view only the simple "next Step on Tap". Correct me if I am wrong.

2. If I don't give a `TextStyle` to a text in the builder, no default Style is applied. I would expect that in this case the theme of my app is used and the text looks exactly like if I create a simple `Text('MyText')` widget outside of onboarding.

3. Maybe a new feature rather than a bug: is there a way to jump to the next step when tapping on the focused widget? The event is then passed to the child or not based on the `overlayBehavior` but I want to go to the next step at that moment. I could imagine to set this directly as a bool, but more flexible would be an `onTapCallback(TapArea tapArea, VoidCallback nextStep, VoidCallback close)`, then everyone could decide how to handle the tap. Of course this only makes sense in combination with `manualControl == true`. Do you understand what I mean? Because it would be practical if you want to declare e.g. a `FAB` that opens an `Alert`, that you actually open this `Alert` when the user clicks on the `FAB` and jumps to the next `onBoardingStep`. This would be a very useful addition from my point of view.

4. If I set `showPulseAnimation = true` at one step it will be shown at all steps, even if `showPulseAnimation` is `null` or `false` at the next step.

**Comment by talamaska** [comment]
> You write nextStep and close work only if manualControl == true
Will fix that. There should not be duplicating/conflicting gestures.

> If I don't give a TextStyle to a text in the builder, no default Style is applied
Yep, you have to apply the style that is provided in the builder. You are on you own here. I can't apply any styles to the widgets that are passed in the builder. Probably i should mention this in the docs.

> Maybe a new feature rather than a bug: is there a way to jump to the next step when tapping on the focused widget?
I understand, but i think this complicates too much the behavior. You could use HitTestBehavior.translucent. Then tap are going to be triggered on the widget and on the overlay. and you can go to nextStep and open your Alert. 

> If I set showPulseAnimation = true at one step it will be shown at all steps, 
Will take a look, this is a bug. the flag should be only for one a specific step

**Comment by talamaska** [comment]
The problem I have is that. The onboarding cannot know if there is a close button defined, and if set magically ignore the global gesture detector when clicked on it. Maybe with a special key? Hm interesting.

**Comment by talamaska** [comment]
@guenth39 Here is what i have tested. I could add an additional property to the OnbardingStep - closeKey. it should be a GlobalKey. If it is set and it is attached to a widget(a button) In the gesture detector i can check if the tap coordinates are within this RenderBox. And if they are, ignore the onTap. This would be independent of the manualControl bool. So manualControl would just make it possible to make you own call to nextStep. and the closeKey would control if you have your own close button. So you can have one but not another. You could have just close, but still be possible to go to next step by clicking anywhere else on the overlay. What to test that out in a separate branch?

**Comment by talamaska** [comment]
https://github.com/talamaska/onboarding_overlay/tree/feature/3.0.0-pre.5

**Comment by guenth39** [comment]
Hey @talamaska I just tried it and it looks all good. But one thing I still do not understand. 

>> Maybe a new feature rather than a bug: is there a way to jump to the next step when tapping on the focused widget?
>
> I understand, but i think this complicates too much the behavior. You could use HitTestBehavior.translucent. Then tap are going to be triggered on the widget and on the overlay. and you can go to nextStep and open your Alert.

But if I do it this way, I would have to open the alert manually, the tap event would not arrive at the widget. This may work in this simple example but in most cases you need specific information from the widget and so it doesn't work. 
Can you explain again why it would be too complicated to add an additional `OnTapCallback` to the `OnboardingStep`? Then the original event would simply be passed to the underlying widget and I could manually call the next step. If I'm not mistaken this would only affect [Stepper:486-490 ](https://github.com/talamaska/onboarding_overlay/blob/b421cb4ce02853a215f57e977697d1a1257e6078/lib/src/stepper.dart#L486) or am I wrong? For clarification here an example:
```dart
OnboardingStep(
  focusNode: focusNodes[0],
  title: 'Tap to the highlighted widget to continue ',
  titleTextColor: Colors.black,
  bodyText:
      'If you tap to the highlighted area the widgets nativ on tap action will be triggered and the next step is called',
  labelBoxPadding: const EdgeInsets.all(16.0),
  fullscreen: true,
  manualControl: true,
  onTapCallback: (TapArea tapArea, VoidCallback next, VoidCallback close){
    if(tapArea == TapArea.hole){
      next();
    }
    // If the tapArea == TapArea.overlay i can do other things or nothing
  }
),
```

**Comment by talamaska** [comment]
> But if I do it this way, I would have to open the alert manually, the tap event would not arrive at the widget. Right?
I'm probably misunderstanding. Let me ask more question to understand better. 
Can this Alert be opened without the onboarding? Is it openable from a button with onTap or onPress?
If yes, what do you mean by "open the alert manually"?
Why do you need to call next manually?

As said above. If you set `overlayBehavior` to `HitTestBehavior.translucent`, the gesture will be triggered on both your button and my overlay, thus opening your Alert and my next method.
Isn't that what you want to achieve?

P.S. I think i have found an issue with the translucent. Lie it doesn't work at all.

If I add onTapCallback I need to add logic to ignore the default behavior and this won't be straightforward.

**Comment by talamaska** [comment]
I need some time to think about it. i didn't expect this HitTestBehavior.translucent to not work :(

**Comment by talamaska** [comment]
@guenth39 I made some experiments. I hade to make quite a lot of changes to make this work. And event them it's like on one wrong move of breaking. Especially if you have showing and hiding elements - you suggested with Alert I tried with a drawer. same logic. I can open the drawer trough the overlay, but the closing is an issue. When next is called it tries to animate the overlay and the hole, but it can't find the hole cause the element is not in the tree and I get an exception.
From the beginning I wanted to avoid such stuff, that's why I didn't implement it initially. I'm not sure what to do. Will look a bit more, and I can't figure it out, gonna move one.

**Comment by talamaska** [comment]
@guenth39 pushed, made some fixes. and implemented onTapCallback. check readme and changelog
still on that branch
https://github.com/talamaska/onboarding_overlay/tree/feature/3.0.0-pre.5

**Comment by guenth39** [comment]
I have just tested the latest version and really like the changes! From my perspective, it is without `manualNextControl` and without `closeKey` again much cleaner. 
The `onTapCallback` also works for me, but unfortunately it is not called when `overlayBehavior == OverlayBehavior.deferToChild` and I tap `TapArea.hole`. Is this just not possible or is this a bug?

**Comment by talamaska** [comment]
Yeah I think it should be always deferToOverlay if you want to use the onTapCallback, else the click on the overlay is ignored and the hitTest is not checked. Will see if I can set an assert and add some docs.

**Comment by guenth39** [comment]
But then the original goal that the tap reaches the widget in the hole and I additionally do something in the `onTapCallback` can not be achieved? I think the `onTapCallback` should always be called, regardless of whether the event is forwarded afterwards or not. Whether you use it or not is another thing. But if `HitTestBehavior.translucent` doesn't work, of course it doesn't work. Unfortunately for me this is the only UseCase of the `onTapCallback` I need :(

Theoretically it should be enough to replace [Stepper:444](https://github.com/talamaska/onboarding_overlay/blob/128f502ae833e71396ff2690622aa65be97f124d/lib/src/stepper.dart#L444) with `HitTestBehavior.translucent` or? But that was the thing that doesn't work or?

**Comment by guenth39** [comment]
Maybe this helps: https://github.com/flutter/flutter/issues/18450

**Comment by talamaska** [comment]
For more clarity of how translucent works read here.  
https://github.com/flutter/flutter/issues/92103
https://github.com/flutter/flutter/issues/74733
https://github.com/flutter/flutter/issues/28170
if the HitTestBehavior is deferToChild, then my GestureDetector is not called at all, when you click on the widget in the hole. So if my GestureDetector is called, then I can't call magically the onTapCallback.
That's how it is.

**Comment by talamaska** [comment]
Maybe there is something I can do. Like it depends if I use GestureDetector or Listener.

**Comment by guenth39** [comment]
Okay, I got it! But it must be somehow possible that the underlying widget can receive the event... Unbelievable that this is so complicated! But I also think that using the listner is a hot track. I'm playing around with it a bit right now as well.

**Comment by talamaska** [comment]
Yes, testing, I think I made it, just verifying if everything is as expected. Thanks for your patience and QA for me :)

**Comment by guenth39** [comment]
I have to thank for your effort! 
For me it works with the `Listener`. I just replaced the `GestureDetector` with a `Listener` and then it works if i use `HitTestBehavior.translucent`

**Comment by talamaska** [comment]
I think that if onTapCallback is set, then the internal call to next step should be bypassed. Do you agree?

**Comment by talamaska** [comment]
published [3.0.0-pre.7](https://pub.dev/packages/onboarding_overlay/versions/3.0.0-pre.7)

**Comment by guenth39** [comment]
Love it! I found no 🐛 and I am very happy with the result ✅ 
It was a pleasure working with you. Let's see how long it takes before I miss the next thing 😅

**Comment by guenth39** [comment]
Ups, rejoiced too soon... one minor suggestion: I think we could remove `step.stepBuilder == null` from the `_nextStep()` check? Or is that still necessary? I think `onTapCallback` is enough.

**Comment by talamaska** [comment]
Right, cause if you have stepBuilder and you have the exposed callbacks it's up to you to call them, cause in other case nexsStep will be called and your buttons will not work :)
