### ISSUE TITLE
Overlay wrong positioned

### ISSUE THREAD

**Issue by jlnrrg** [talamaska/onboarding_overlay#24]
This is probably a bug that will not concern many people, so feel free to ignore it.

When the in `Onboarding` capsulated Page shares the screen with another widget (for example a Drawer) the overlay is not positioned correctly.

e.g Pseudo Code
```dart
Row(
  children: [
    Drawer(),
    Onboarding(child: Scaffold()),
);

```

In this case I encapsulated the "Export Data" Button with the Focus, but the overlay was positioned to the right.
![Screenshot from 2021-12-03 13-04-10](https://user-images.githubusercontent.com/77293597/144599689-cd8fb8f9-312b-4450-80c2-6d45e3dfa664.png)

**Comment by jlnrrg** [comment]
I again want to stress that this is most likely not a bug of this package, just want to make people after me aware of it.
It seems to be related to flutters `showMenu` function, which also behaves the same way in the giving situation.

**Comment by talamaska** [comment]
What happens if you move the onboarding widget above the row in the widget tree?
I also see that the overlay is not covering your drawer.

**Comment by talamaska** [comment]
If you send me more minimal reproducing code i could test it out if it works with rootOverlay  = true

**Comment by jlnrrg** [comment]
If I place the overlay on top, it looks better, but still is miss alligned.

![Screenshot from 2021-12-03 13-22-48](https://user-images.githubusercontent.com/77293597/144601926-5a21ab16-7f05-4a59-aae2-7721d4081aab.png)

Edit: I found out that this has to do with the [ResponsiveFramework](https://pub.dev/packages/responsive_framework) 's scaling. And now, when setting scaling to 1, it aligns perfect.
![Screenshot from 2021-12-03 13-27-25](https://user-images.githubusercontent.com/77293597/144602467-f0576748-531b-43b3-88c7-30202b7031d4.png)

**Comment by jlnrrg** [comment]
It was not easy to create a minimal example, as everything worked fine in the beginning.
Then I found out, that it might have something to do with the use of [auto_route](https://pub.dev/packages/auto_route), so I also included this. 
Now you can look at the [minimal example](https://github.com/jlnrrg/flutter_overlay_test) and try things out.
If you have any more questions, feel free to ask and thanks for your support :smile:.

**Comment by talamaska** [comment]
Ok, to be clear, I'll check only the the context for the overlay. And last - is this a desktop app? Should I test only on large screens.

**Comment by talamaska** [comment]
Ok tested with rootOverlay, looks ok.
But I would not enforce it, Cause you are the first of reporting such issue, I would prefer having a setting like globalOnboarding: true/false and if you set it to true make the rootOverlay = true.

**Comment by talamaska** [comment]
check release [3.0.0-pre.10](https://pub.dev/packages/onboarding_overlay/versions/3.0.0-pre.10)

**Comment by jlnrrg** [comment]
Yes, it is a desktop app.
Great work with the new pulse animation, but unfortunately this new version did not fix the issue :frowning_face:
![Screenshot from 2021-12-04 14-14-30](https://user-images.githubusercontent.com/77293597/144710823-ef78cbc1-97db-4a79-98b2-7581c390888b.png)
.

**Comment by talamaska** [comment]
I have tested with your example app and it was working fine with the new setting set to true. It was also with auto route, no? I'm not sure how good practice would be to pass to the widget a context. The only place I have seen this practice was in showDialog, where it is used to get the Navigator of this context. But the function is detached from the widget tree. While my onboarding widget is declared in the widget tree and that's how it gets the context. If you want the onboarding overlay to cover the whole app, then you mist decalre it on top of everything underneath a MaterialApp. I'm already in doubt how great was the idea to put this new setting and probably will remove it before the stablw v.3 release.

**Comment by jlnrrg** [comment]
It seems that I totally overlooked the new parameter `globalOnboarding`. 
With this set to true, it now works as intended in the example app. 
Sorry for your inconvenience based on my missunderstanding. There is no need now to pass additional context from my pov.
And thank you for the fast support :smile:
