### ISSUE TITLE
Desktop App resizing issue

### ISSUE THREAD

**Issue by jlnrrg** [talamaska/onboarding_overlay#26]
First of all, I have yet to replicate this with my [overlay_test_app](https://github.com/jlnrrg/flutter_overlay_test), because there it works fine, I assume some kind of incompatibility with another package.

I think the video should explain the issue quite well.
If you have an idea, or encountered the problem at a certain point, feel free to share, otherwise I just use this issue to track my reproduction progress :smile:.

Steps taken:
- [x] removed [responsive_framework](https://pub.dev/packages/responsive_framework) dependency

https://user-images.githubusercontent.com/77293597/145116858-3eb85acc-2eb9-46b9-a965-2f9f9bc2b0d0.mp4

Edit:
The error message in the end is: (over and over again)
```bash
Invalid argument(s): 0.0
The relevant error-causing widget was
MaterialApp
lib/main.dart:122
```

**Comment by talamaska** [comment]
it seems to me that this is caused by some clamping on the position of the label box.
I'll need some time to debug and figure out what is going on.
And also I wonder why your overlay is not full screen at some point.

**Comment by jlnrrg** [comment]
> And also I wonder why your overlay is not full screen at some point.
yeah, it is kind of a multiple step issue:
1. not full screen on resizing (minus)
2. error message on certain size (big)

**Comment by talamaska** [comment]
clamping issue is reproducible and I'm going to make a fix tomorrow.
the other issue I can't reproduce.

**Comment by jlnrrg** [comment]
Ok, I reproduced the issue and I feel stupid :expressionless:
I had set for every `OnboardingStep` the `fullscreen` to false.

Hope this will help someone else in the future.

On another note:
Can you explain (or show an image) what the Arrow intends to do (`hasArrow`).

(I will close the issue, once the new version fixes the other issue)
> 2. error message on certain size (big)

**Comment by talamaska** [comment]
![image](https://user-images.githubusercontent.com/299973/145213291-372faed4-16ab-494d-a15f-c57e0004afb8.png)
![image](https://user-images.githubusercontent.com/299973/145213325-54c2e55b-6aac-44be-9b95-1b2060122301.png)
![image](https://user-images.githubusercontent.com/299973/145213365-08fd3a9e-abb1-4606-8bc7-9c24f6e54b4d.png)
![image](https://user-images.githubusercontent.com/299973/145213400-e06edcd8-f861-4a58-818c-f7495bca1524.png)

Hope those help.

**Comment by jlnrrg** [comment]
It does indead.
I was mainly inquiring to find an easy fix to repositioning the text, as the desktop draws it quite to the start :sweat_smile:.
![Screenshot from 2021-12-08 14-09-49](https://user-images.githubusercontent.com/77293597/145214059-51f0ef31-73d8-43bc-842e-26d166607995.png)

But then I found out that you use `textAlign` to handle this. 
The issue then is, that (obviously :smile:) the text is not left aligned anymore:

![Screenshot from 2021-12-08 14-12-25](https://user-images.githubusercontent.com/77293597/145214347-7fdfc24e-c5a5-49bf-8161-5a92cbb98b41.png)

**Comment by talamaska** [comment]
There is no silver bullet here. I've never targeted this plugin for larger screens. You might want to calculate the desired width put it in a sizedbox and a row and all that placed in a stepBuilder. Also you can use the debugBoundaries flag to understand how much space is allocated for the label. On full screen it takes as much as possible, on fullscreen false it's kinda limited I'm still searching for the equation that will gibe the right size of the label box, as the overlay could be a different shape.

**Comment by talamaska** [comment]
3.0.0-pre.13
