### ISSUE TITLE
Overlay not centered in the floatingActionButton

### ISSUE THREAD

**Issue by Macacoazul01** [talamaska/onboarding_overlay#28]
I'm having this bug that the overlay isn't centered on my `floatingActionButton` inside the bottom bar:

![image](https://user-images.githubusercontent.com/57464965/147268631-cfc8ee4a-2703-40f2-9309-686e3e1b36dd.png)

lib version: `onboarding_overlay: ^2.3.5`

I don't know if this is fixed on the 3.0 pre-release (do you have any estimate when it will be released?)

sample code:
[center.zip](https://github.com/talamaska/onboarding_overlay/files/7770470/center.zip)

**Comment by talamaska** [comment]
Could you please check the pre-release version. I have this working pretty well.
![image](https://user-images.githubusercontent.com/299973/147274564-56995438-4992-4f90-ac1a-13468166fb91.png)

**Comment by Macacoazul01** [comment]
Same behavior with the pre-release
I don't know if it's something related to this package or where [animated_bottom_navigation_bar](https://pub.dev/packages/animated_bottom_navigation_bar) renders the fab as the margin parameter helps with this.

using `margin: EdgeInsets.fromLTRB(10, 10, 15, 15),` both on pre-release and 2.3.5:

![image](https://user-images.githubusercontent.com/57464965/147277128-291beb8c-bef4-44fe-9ced-59751dd4d771.png)

**Comment by talamaska** [comment]
The problem is that you are scaling the Fab. And the scale is not executed from the center.
You can y wrapping the transform widget with focus and attach the focus node to that, instead of the Fab.
Like this
```dart

floatingActionButton: Focus(
          focusNode: focus[0],
          child: Transform.scale(
            scale: 1.1,
            child: FloatingActionButton(
              elevation: 10,
              onPressed: () {
                print('object');
              },
              backgroundColor: Colors.blue,
              child: Center(
                child: Icon(
                  Icons.add,
                  color: Colors.white,
                  size: 30,
                ),
              ),
            ),
          ),
        ),
````
