### ISSUE TITLE
Grey overlay bug on android version 10

### ISSUE THREAD

**Issue by jlnrrg** [talamaska/onboarding_overlay#29]
I am not sure if this counts as a bug report :sweat_smile:
So a few days ago when I did some live testing on different android devices of my friends. I encountered a bug which is very likely linked to the onboarding_overlay, as it appeared where and when the overlay appeared and was dismissed how I set it up for the overlay.

Long story short:
Instead of the colored overlay with text etc. a grey overlay appeared where no text could be seen.
I was not able to track down the bug but one thing both devices had in common where the android version 10.
If someone else had this bug appeared previously, I am happy for your comment. 
Otherwise I'll use this issue to track my progress.

**Comment by talamaska** [comment]
Will check on emulator Android v10, but other than that I'm not sure how I would be able to reproduce something.
I don't use anything "native" so that the OS version could have anything related.
If you are able to specify precise steps to reproduce  would gladly take a deeper look. It is possible that I have missed some assert or something else. In any case could you check with pre-release version 
https://pub.dev/packages/onboarding_overlay/versions/3.0.0-pre.15

**Comment by jlnrrg** [comment]
I might have followed the problem down the rabbit hole.
I use the following widget under `Onboarding(child: ` 

<details><summary>Show Onboarding on first start - Widget</summary>

```dart

class _OnboardingFocus extends StatefulWidget {
  const _OnboardingFocus({Key? key, required this.child}) : super(key: key);

  final Widget child;

  @override
  _OnboardingFocusState createState() => _OnboardingFocusState();
}

class _OnboardingFocusState extends State<_OnboardingFocus> {
  @override
  void initState() {
    super.initState();

    WidgetsBinding.instance?.addPostFrameCallback((Duration timeStamp) {
      final onboarding = Onboarding.of(context);
      onboarding?.show();
    });
  }

  @override
  Widget build(BuildContext context) {
    return widget.child;
  }
}
```
</details>


Everything works as intended, but there is a use case where my router pushes a nested route.
Where the onboarding is in GamePageRoute:

`context.navigateTo(
            GameTab(children: [const GamePageRoute(), RoundEditPageRoute()]));`

so now the routes are pushed fast in this order:
GameTab -> GamePageRoute -> RoundEditPageRoute

<details><summary>Error message</summary>

```bash
════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building LayoutBuilder:
RenderBox was not laid out: RenderSemanticsAnnotations#9a99c NEEDS-LAYOUT NEEDS-PAINT
'package:flutter/src/rendering/box.dart':
package:flutter/…/rendering/box.dart:1
Failed assertion: line 1927 pos 12: 'hasSize'

The relevant error-causing widget was
MaterialApp
lib/main.dart:137
When the exception was thrown, this was the stack
#2      RenderBox.size
package:flutter/…/rendering/box.dart:1927
#3      _OnboardingStepperState.calcWidgetRect
package:onboarding_overlay/src/stepper.dart:283
#4      _OnboardingStepperState.initState
package:onboarding_overlay/src/stepper.dart:152
#5      StatefulElement._firstBuild
package:flutter/…/widgets/framework.dart:4728
#6      ComponentElement.mount
package:flutter/…/widgets/framework.dart:4561
#7      Element.inflateWidget
package:flutter/…/widgets/framework.dart:3631
#8      Element.updateChild
package:flutter/…/widgets/framework.dart:3383
```
</details>

**Comment by talamaska** [comment]
there is probably some animation in the router that takes longer than a frame. I need more info on where is exactly positioned this OnboardingFocus. You can attach a simplified version of your app with the routing and all that as a zip file.
