### ISSUE TITLE
hasArrow property doesn't seem to work

### ISSUE THREAD

**Issue by mack-myers** [talamaska/onboarding_overlay#3]
@talamaska @lucaslcode  hi there - I'm trying to use this onboarding_overlay package in my Flutter project and so far I'm having success. One thing I am trying to determine is whether or not we can include a button to trigger the next index. I see the `OnboardingStep()` constructor includes a `hasArrow` property, but this doesn't seem to do anything.

After looking at the code, it seems there isn't any dynamic functionality using this property. Is this a simple fix?

**Comment by talamaska** [comment]
Thanks for finding this issue. I'm not sure if this is something I haven't started or removed that feature. I'll take a look next week and get back to you

**Comment by talamaska** [comment]
on quick look, it was something that I started and never finished. It's complicated and might take a while. stay tuned.

**Comment by mack-myers** [comment]
@talamaska amazing. Thank you for the quick reply. I'll stay tuned. Let me know if I can assist in any way. Our goal is to include a nice material button or fab to navigate next (and optionally previous). Perhaps located under the title/bodyText and left-aligned.

**Comment by talamaska** [comment]
@mack-myers about that I'm not sure this package will ever support buttons inside the onboarding step. just because there is a global gesture detector.
Now about the arrows, What I initially envisioned was just a vertical arrows, I'll have to figure out how to make the calculations a bunch of other things that all need to happen in a custom painter.

**Comment by mack-myers** [comment]
@talamaska no problem! do you mean horizontal arrows? Seems more intuitive for next/previous. Thank you for looking into this!

**Comment by talamaska** [comment]
No, arrows are for pointing out to the widget of interest, not for navigation. The one that has a focusNode. You can have only one arrow at a time. The arrows are not clickable. There is only one direction of watching the onboarding - forward. I haven't tried but, there is a method to run the onboarding with certain steps , from a certain step. You can try setting the indexes in the array in the order you want, not in the order they were declared in the onboarding widget.

**Comment by talamaska** [comment]
fixed with #4 

released with 2.1.0
