### ISSUE TITLE
No rebuild of overlay on screen update

### ISSUE THREAD

**Issue by jlnrrg** [talamaska/onboarding_overlay#30]
I noticed this previous when resizing a desktop window, that the overlay hole does not resize correctly.
But as this is a minor case ... so be it.

But now I noticed that this creates an issue when using ads. Which are only displayed after getting data.

https://user-images.githubusercontent.com/77293597/147824925-eb7e967c-6fc4-43d4-945b-e0f907f00558.mp4

**Comment by talamaska** [comment]
Please check in v3 about the the desktop issue.
please attach a minimal replication code. The onboarding has a layout builder and should rebuild when the screen size changes.
But on this mobile screen I don't see screen changing.
