### ISSUE TITLE
 Check in integration test if onboarding is shown

### ISSUE THREAD

**Issue by CaptainDario** [talamaska/onboarding_overlay#35]
Basically, what the title says, I am trying to check if the onboarding is shown in my integration test.
I tried checking for the text with `find.byText()` but this does not seem to work.

Do you know of any way to check this?

**Comment by talamaska** [comment]
Unfortunately I have not made any tests for it. I know that overlay is detached from the widget tree, so I'm not sure if the finder will detect it. The overlay is animated, so you need to run pumpAndSettle before writing your expects. Seems this SO is solving that answer.
https://stackoverflow.com/questions/62828221/how-to-test-overlay
