### ISSUE TITLE
[question] Execute code after Onboarding.of(context)!.show();

### ISSUE THREAD

**Issue by Macacoazul01** [talamaska/onboarding_overlay#36]
Today if i try to execute something on the next line after `Onboarding.of(context)!.show()` it will run before the end of the onboarding steps.

Is there any way of "waiting" the end of onboarding steps to execute the code (something like this function becoming async) or the only way is adding some function to `onTapCallback` of the last `OnboardingStep` widget?

**Comment by talamaska** [comment]
the Onboarding widget has a callback onEnd, which is called after the last step

**Comment by Macacoazul01** [comment]
Can you give any sample on how to use it?

**Comment by talamaska** [comment]
```dart
Onboarding(
  key: onboardingKey,
  steps: getSteps(al, theme, focusNodes),
  autoSizeTexts: true,
  onEnd: (int index) {
    onboardingStore.updateOnboardingCompleted(true); // MobX, Store, ChangeNotifier, Cubit w/e 
  },
  globalOnboarding: true,
  child: Scaffold(...)
)
```
