### ISSUE TITLE
Highlighting issue

### ISSUE THREAD

**Issue by Erkapos** [talamaska/onboarding_overlay#41]
The issue that i'm facing is on some occassion only, usually when it changes page, the highlight from the new page is not sync with the widget that i want to highlight. for now, my speculation is that, it's because of flutter animation when changing page. I'm calling the showfromindex at initstate, if it affects anything. 

is there anyway i can fix this issue ?

the issue that i mentioned, is drawn below
![image](https://user-images.githubusercontent.com/68910543/202098085-844f2d28-1ed1-4c0f-8f8e-7dcc572342a0.png)

**Comment by talamaska** [comment]
Maybe you should call the showFromIndex after the animations have finished?

**Comment by Erkapos** [comment]
> Maybe you should call the showFromIndex after the animations have finished?

**Comment by Erkapos** [comment]
> Maybe you should call the showFromIndex after the animations have finished?

that's the problem, i only use the default page transition from flutter, and what i've found on stackoverflow is to use WidgetsBinding.instance.addPostFrameCallback (i already done it since it is a must when calling onboarding from initstate) and adding a timer(), but using a timer seems too brute force, any other stuff that i can try ?

**Comment by talamaska** [comment]
Actually I've been doing the same, I had one giant onboarding with 15 + steps and was launching it with showFromIndex. 
I didn't had any issues with that, except that I had some headaches around tracking, cause I'm saving in db and I'm using mobx and reactions were odd. At some point I just separated this giant onboarding into 3 smaller ones. I'm using PageView widget to navigate between pages and I only have bottom bar to navigate between. If you can share a portion of the code that I can use to reproduce, I can try dig into it. I don't have a lot of ideas.

**Comment by Erkapos** [comment]
Since it isn't consistent and the code is confidential, i don't think i can give the code and reproduce the error.  And so do you use timer () with it ? any other things ?

**Comment by talamaska** [comment]
No, I don't use timer. Well you can create a code that is not confidential :) I need a code that reproduces this problem at least sometimes.
