### ISSUE TITLE
How do i show last onboarding shown after hidden

### ISSUE THREAD

**Issue by Erkapos** [talamaska/onboarding_overlay#43]
So i want to show the latest onboarding steps that have been shown after it has been hidden. is there any way i can achieve this ?

the sequence is
onboarding step 3 -> hide onboarding using .hide() -> show onboarding step 3 again but not using showfromindex

**Comment by Erkapos** [comment]
i want to keep track on where is the onboarding step is currently, but i can't do that by using the onChanged index because not every step that i do, i use nextStep, sometimes i use showfromindex again to show it.

**Comment by talamaska** [comment]
Well, you could show last step - 1, no?
