### ISSUE TITLE
overlay show checker

### ISSUE THREAD

**Issue by Erkapos** [talamaska/onboarding_overlay#44]
is there a way to check if overlay is currently showing because i want to achieve a code like this

if(overlay is shown ?){
hide overlay here
}

**Comment by talamaska** [comment]
you can use the onboarding reference gotten by key or Onboarding.of(context), then use the exposed controller.
```dart
onboarding.controller.isVisible;
```

Or extend it with an extension
```dart
extension VisibilityOnboarding on OnboardingState {
  bool isVisible() {
    return controller.isVisible;
  }
}
```

**Comment by Erkapos** [comment]
ok ok thank you very much, it works
