### ISSUE TITLE
Title/Body Positioning and LabelBox Width Not Able to Be Manipulated

### ISSUE THREAD

**Issue by K-shimrock-mesh** [talamaska/onboarding_overlay#5]
@lucaslcode @talamaska hello - This package has been working great, but it seems as if I'm unable to manipulate the positioning of title/body texts within the overlay, as well as manipulate the labelBoxes to fit the width of my paragraph. I have attempted to manipulate the labelBoxPadding property, but that did not seem to provide any solution. Is there anything you suggest to help fix this problem? 

Thanks!

**Comment by talamaska** [comment]
Manipulating the width of the label box was never intended, it could lead to really unwanted behavior and hard to control side effects. The position of the label box is somewhat pre-calculated depending on the position of the focused widget position. Look at line 30 in stepper.dart. Place shorter texts or manipulate the textStyle, like making smaller font.
