### ISSUE TITLE
Can't find onboarding widget

### ISSUE THREAD

**Issue by BenoitDuffez** [talamaska/onboarding_overlay#57]
Here's the error I have:

```
The following assertion was thrown during a scheduler callback:
No Onboarding widget found.

Accessing the OnboardingState with Onboarding.of(context) needs an Onboarding widget ancestor

The most common way to add an Onboarding to an application is to include it, below MaterialApp widget in the runApp() call.

The context from which that widget was searching for an OnboardingState was: LicheApp
```

The widget hierarchy is:

![image](https://github.com/talamaska/onboarding_overlay/assets/802209/6544fecd-1277-446f-9286-e06345d65d3a)

I have triggered the show from `HomePage`:

```
class HomePage extends StatefulWidget {
  const HomePage({super.key, [...], required this.focusNodes});

  // ...
  final List<FocusNode> focusNodes;

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  @override
  void initState() {
    super.initState();
 
    WidgetsBinding.instance.addPostFrameCallback((Duration timeStamp) {
      print("showing onboarding");
      Onboarding.of(context)?.show();
    });
 }

  ...
}
```

I also tried to call `Onboarding.of(context)?.show()` from a button click in the UI but it yields the same result.

I am not sure what I did wrong?

**Comment by BenoitDuffez** [comment]
OK, my material app is handled by https://pub.dev/packages/go_router — maybe this isn't supported?

In my gorouter config I changed this:

```
        builder: (BuildContext context, GoRouterState state) => HomePage(db: db),
```

into this:

```
          var homePage = HomePage(db: db, focusNodes: focusNodes);


          final List<OnboardingStep> steps = [
            OnboardingStep(focusNode: focusNodes[0],
              ...
          ];

          return Onboarding(key: onboardingKey,steps: steps, child: homePage);
```

and now it works. I guess I just need to properly insert the `Onboarding` widget in the tree. Feel free to close if this is the expected behavior.

**Comment by talamaska** [comment]
I had some issues accessing Provided bloc when using go_router, in turned out that the modals are launched with the default navigator, which for some reason doesn't access the same context as go_router. So I don't know.

**Comment by BenoitDuffez** [comment]
Gorouter creates the widgets which are then inserted into the tree, so now I'm creating the onboarding wrapper there, and it works. I guess we can close.
