### ISSUE TITLE
Needs an Onboarding widget ancestor

### ISSUE THREAD

**Issue by PfernFSU** [talamaska/onboarding_overlay#61]
Hello,

I am using the latest version (3.2.2) and am hitting a weird issue similar to [this](https://github.com/talamaska/onboarding_overlay/issues/57) but not quite. It says it cannot find the Onboarding widget, but it is clearly there in the widget tree. I have a Scaffold and in the appBar I am trying to toggle this via a gestureDetector. Below you can see my code and also see the widget tree. I don't need to pass the focus nodes used in the steps as you can see from the screenshot below I create them on the fly. The Onboarding is clearly in the widget tree, both in terms of the code and also the flutter dev tools. I have used this Onboarding in several other places in the app without issues (it works great as a help screen in case the user is unsure what options are available).

Widget Hierarchy showing Onboarding as the root:
![image](https://github.com/user-attachments/assets/b0300749-019f-4f5f-a8b9-c250787ee799)

Code showing the Onboarding as a parent widget along with the nodes creation and the exception:
![image](https://github.com/user-attachments/assets/4e5553d4-e92b-4c3e-870d-0db7e6df0c23)

**Comment by PfernFSU** [comment]
So after going over the docs with a fine-toothed comb I found the issue. The docs do say it needs to be a separate BuildContext, and when I moved the Scaffold to a new widget it worked. I still can't wrap my head around why it needs a new BuildContext and must be in a separate widget, but that solved the issue.

![image](https://github.com/user-attachments/assets/15baa40d-874b-4cef-9c9f-a8bbab43b1e9)

**Comment by talamaska** [comment]
The new context is required, cause there is a Stateful widget State that tracks the state of the onboarding. It is searched up in the widget tree like the inherited widgets or Providers, so you need at least a Builder widget to access the closest instance. Not sure how the dynamic focus nodes would work at all.
