### ISSUE TITLE
is it possible to make it run only once and when it enters the page?

### ISSUE THREAD

**Issue by iagognunes** [talamaska/onboarding_overlay#7]
I would like to know if it is possible to make it run only when you first enter the page.

**Comment by talamaska** [comment]
Sure, you must control that logic yourself. For example, I have a table in my local db, but you can do it with other storage solution, a state management solution that links to the storage on app run and checks if the onboarding was run or not. by using the callbacks provided I was able to detect the last step and save that the onboarding was passed. You can go even further and separate multiple steps in different pages. and save all the data in the db and the store(state) and launch certain slices of the number of the steps you have configured for different pages.

**Comment by iagognunes** [comment]
Thanks for helping me!
